package ucesoft.smd.cpu.m68k

enum InstructionType(val mnemonic:String,
                     val needsSupervisorMode:Boolean = false):
  case ABCD           extends InstructionType("abcd")
  case ADD            extends InstructionType("add")
  case ADDA           extends InstructionType("adda")
  case ADDI           extends InstructionType("addi")
  case ADDQ           extends InstructionType("addq")
  case ADDX           extends InstructionType("addx")
  case AND            extends InstructionType("and")
  case ANDI           extends InstructionType("andi")
  case ANDI2CCR       extends InstructionType("andi")
  case ANDI2SR        extends InstructionType("andi",needsSupervisorMode = true)
  case ASL            extends InstructionType("asl")
  case ASR            extends InstructionType("asr")
  // Bcc
  case BCC            extends InstructionType("bcc")
  case BCS            extends InstructionType("bcs")
  case BEQ            extends InstructionType("beq")
  case BGE            extends InstructionType("bge")
  case BGT            extends InstructionType("bgt")
  case BHI            extends InstructionType("bhi")
  case BLE            extends InstructionType("ble")
  case BLS            extends InstructionType("bls")
  case BLT            extends InstructionType("blt")
  case BMI            extends InstructionType("bmi")
  case BNE            extends InstructionType("bne")
  case BPL            extends InstructionType("bpl")
  case BVC            extends InstructionType("bvc")
  case BVS            extends InstructionType("bvs")
  case BRA            extends InstructionType("bra")
  case BSR            extends InstructionType("bsr")

  case BCHG           extends InstructionType("bchg")
  case BCLR           extends InstructionType("bclr")
  case BSET           extends InstructionType("bset")
  case BTST           extends InstructionType("btst")

  case CHK            extends InstructionType("chk")
  case CLR            extends InstructionType("clr")
  case CMP            extends InstructionType("cmp")
  case CMPA           extends InstructionType("cmpa")
  case CMPI           extends InstructionType("cmpi")
  case CMPM           extends InstructionType("cmpm")
  // DBcc
  case DBT            extends InstructionType("dbt")
  case DBRA           extends InstructionType("dbra")
  case DBCC           extends InstructionType("dbcc")
  case DBCS           extends InstructionType("dbcs")
  case DBEQ           extends InstructionType("dbeq")
  case DBGE           extends InstructionType("dbge")
  case DBGT           extends InstructionType("dbgt")
  case DBHI           extends InstructionType("dbhi")
  case DBLE           extends InstructionType("dble")
  case DBLS           extends InstructionType("dbls")
  case DBLT           extends InstructionType("dblt")
  case DBMI           extends InstructionType("dbmi")
  case DBNE           extends InstructionType("dbne")
  case DBPL           extends InstructionType("dbpl")
  case DBVC           extends InstructionType("dbvc")
  case DBVS           extends InstructionType("dbvs")

  case DIVS           extends InstructionType("divs")
  case DIVU           extends InstructionType("divu")

  case EOR            extends InstructionType("eor")
  case EORI           extends InstructionType("eori")
  case EORI2CCR       extends InstructionType("eori")
  case EORI2SR        extends InstructionType("eori",needsSupervisorMode = true)

  case EXG            extends InstructionType("exg")
  case EXT            extends InstructionType("ext")
  case ILLEGAL        extends InstructionType("illegal")
  case JMP            extends InstructionType("jmp")
  case JSR            extends InstructionType("jsr")
  case LEA            extends InstructionType("lea")
  case LINK           extends InstructionType("link")
  case LSL            extends InstructionType("lsl")
  case LSR            extends InstructionType("lsr")
  case MOVE           extends InstructionType("move")
  case MOVEA          extends InstructionType("movea")
  case MOVEFromSR     extends InstructionType("move")
  case MOVEToCCR      extends InstructionType("move")
  case MOVEToSR       extends InstructionType("move",needsSupervisorMode = true)
  case MOVEUSP        extends InstructionType("move",needsSupervisorMode = true)
  case MOVEM          extends InstructionType("movem")
  case MOVEP          extends InstructionType("movep")
  case MOVEQ          extends InstructionType("moveq")
  case MULS           extends InstructionType("muls")
  case MULU           extends InstructionType("mulu")
  case NBCD           extends InstructionType("nbcd")
  case NEG            extends InstructionType("neg")
  case NEGX           extends InstructionType("negx")
  case NOP            extends InstructionType("nop")
  case NOT            extends InstructionType("not")
  case OR             extends InstructionType("or")
  case ORI            extends InstructionType("ori")
  case ORI2CCR        extends InstructionType("ori")
  case ORI2SR         extends InstructionType("ori",needsSupervisorMode = true)
  case PEA            extends InstructionType("pea")
  case RESET          extends InstructionType("reset",needsSupervisorMode = true)
  case ROL            extends InstructionType("rol")
  case ROR            extends InstructionType("ror")
  case ROXL           extends InstructionType("roxl")
  case ROXR           extends InstructionType("roxr")
  case RTE            extends InstructionType("rte",needsSupervisorMode = true)
  case RTR            extends InstructionType("rtr")
  case RTS            extends InstructionType("rts")
  // Scc
  case ST             extends InstructionType("st")
  case SF             extends InstructionType("sf")
  case SHI            extends InstructionType("shi")
  case SLS            extends InstructionType("sls")
  case SCC            extends InstructionType("scc")
  case SCS            extends InstructionType("scs")
  case SNE            extends InstructionType("sne")
  case SEQ            extends InstructionType("seq")
  case SVC            extends InstructionType("svc")
  case SVS            extends InstructionType("svs")
  case SPL            extends InstructionType("spl")
  case SMI            extends InstructionType("smi")
  case SGE            extends InstructionType("sge")
  case SLT            extends InstructionType("slt")
  case SGT            extends InstructionType("sgt")
  case SLE            extends InstructionType("sle")
  case SBCD           extends InstructionType("sbcd")
  case STOP           extends InstructionType("stop")
  case SUB            extends InstructionType("sub")
  case SUBA           extends InstructionType("suba")
  case SUBI           extends InstructionType("subi")
  case SUBQ           extends InstructionType("subq")
  case SUBX           extends InstructionType("subx")
  case SWAP           extends InstructionType("swap")
  case TAS            extends InstructionType("tas")
  case TRAP           extends InstructionType("trap")
  case TRAPV          extends InstructionType("trapv")
  case TST            extends InstructionType("tst")
  case UNLK           extends InstructionType("unlk")
